SOLVER:
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_NORM: 0.0
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 5000
  WARMUP_METHOD: linear
  GAMMA: 0.1118
  BASE_LR: 0.016
  BIAS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 16