MODEL:
  DEVICE: 'cuda'
  META_ARCHITECTURE: "Dino"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  DINO:
    NUM_CLASSES: 2
    DET_TOKEN_NUM: 100
    BACKBONE_NAME: 'resnet50'
    DILATION: False
    POSITION_EMBEDDING: 'sine'
    PE_TEMPERATUREH: 20
    PE_TEMPERATUREW: 20
    RETURN_INTERM_INDICES: [0, 1, 2, 3]
    BACKBONE_FREEZE_KEYWORDS: None
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    UNIC_LAYERS: 0
    PRE_NORM: False
    DIM_FEEDFORWARD: 2048
    HIDDEN_DIM: 256
    DROPOUT: 0.0
    NHEADS: 8
    NUM_QUERIES: 900
    QUERY_DIM: 4
    NUM_PATTERNS: 0
    PDETR3_BBOX_EMBED_DIFF_EACH_LAYER: False
    PDETR3_REFHW: -1
    RANDOM_REFPOINTS_XY: False
    FIX_REFPOINTS_HW: -1
    DABDETR_YOLO_LIKE_ANCHOR_UPDATE: False
    DABDETR_DEFORMABLE_ENCODER: False
    DABDETR_DEFORMABLE_DECODER: False
    USE_DEFORMABLE_BOX_ATTN: False
    BOX_ATTN_TYPE: 'roi_align'
    DEC_LAYER_NUMBER: None
    NUM_FEATURE_LEVELS: 5
    ENC_N_POINTS: 4
    DEC_N_POINTS: 4
    DECODER_LAYER_NOISE: False
    DLN_XY_NOISE: 0.2
    DLN_HW_NOISE: 0.2
    ADD_CHANNEL_ATTENTION: False
    ADD_POS_VALUE: False
    TWO_STAGE_TYPE: 'standard'
    TWO_STAGE_PAT_EMBED: 0
    TWO_STAGE_ADD_QUERY_NUM: 0
    TWO_STAGE_BBOX_EMBED_SHARE: False
    TWO_STAGE_CLASS_EMBED_SHARE: False
    TWO_STAGE_LEARN_WH: False
    TWO_STAGE_DEFAULT_WH: 0.05
    TWO_STAGE_KEEP_ALL_TOKENS: False
    NUM_SELECT: 300
    TRANSFORMER_ACTIVATION: 'relu'
    BATCH_NORM_TYPE: 'FrozenBatchNorm2d'
    MASKS: False 
    DECODER_SA_TYPE: 'sa'
    DECODER_MODULE_SEQ: ['sa', 'ca', 'ffn']
    NMS_IOU_THRESHOLD: -1
    DEC_PRED_BBOX_EMBED_SHARE: True
    DEC_PRED_CLASS_EMBED_SHARE: True
    USE_DN: True
    DN_NUMBER: 100
    DN_BOX_NOISE_SCALE: 0.4
    DN_LABEL_NOISE_RATIO: 0.5
    EMBED_INIT_TGT: True
    DN_LABELBOOK_SIZE: 2
    MATCH_UNSTABLE_ERROR: True
    USE_DETACHED_BOXES_DEC_OUT: False
    NUM_PROMPTS: 10000
  LOSS:
    AUX_LOSS: True
    DICE_LOSS_COEF: 1.0
    BBOX_LOSS_COEF: 5.0
    GIOU_LOSS_COEF: 2.0
    CLS_LOSS_COEF: 1.0
    MASK_LOSS_COEF: 1.0
    ENC_LOSS_COEF: 1.0
    INTERM_LOSS_COEF: 1.0
    NO_INTERM_BOX_LOSS: False
    FOCAL_ALPHA: 0.25
  MATCHER:
    MATCHER_TYPE: 'HungarianMatcher'
    SET_COST_CLASS: 2.0
    SET_COST_BBOX: 5.0
    SET_COST_GIOU: 2.0
    

SOLVER:
  FROZEN_WEIGHTS: None
  USE_CHECKPOINT: False
  IMS_PER_BATCH: 1
  BASE_LR: 0.0001
  LR_BACKBONE: 0.00001
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  CLIP_MAX_NORM: 0.1
  PARAM_DICT_TYPE: 'default'
  LR_BACKBONE_NAMES: ['backbone.0']
  LR_LINEAR_PROJ_NAMES: ['reference_points', 'sampling_offsets']
  LR_LINEAR_PROJ_MULT: 0.1
  DDETR_LR_PARAM: False
  ONECYCLELR: False
  MULTI_STEP_LR: False
  LR_DROP_LIST: [33, 45]

  # MAX_ITER: 5000 #
  # WARMUP_ITERS: 0 #
  # BASE_LR_END: 0.0000001 #
  # LR_SCHEDULER_NAME: "WarmupCosineLR" #


INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 4000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
VERSION: 2
