_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  WEIGHTS: "X-50-32x4d.pkl"
  # PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    # STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 4
    DEPTH: 50
SOLVER:
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_NORM: 0.0
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 5000
  WARMUP_METHOD: linear
  GAMMA: 0.1118
  BASE_LR: 0.016
  BIAS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 16
